### ISSUE TITLE
MVC aspnet

### ISSUE THREAD

**Issue by thanhtai9606** [servocoder/RichFilemanager#114]
I dont know, how to set root directory in filemanager in ASP.net MVC?
Some body help me??

**Comment by servocoder** [comment]
Do you use ASHX connector?

**Comment by thanhtai9606** [comment]
thank you, I have just change connector by ashx. What'is purpose  MVC connector ???

**Comment by servocoder** [comment]
I think you should know the difference between MVC and ASHX connectors better than me, since I'm PHP developer, not ASP. I can only say that MVC connector is extremely outdated, unlike ASHX which was updated some time ago by @richeflits. You can address your questions on ASHX connector to him. Also I appreciate a contribution, so feel free to improve and extend MVC / ASHX connectors.

**Comment by thanhtai9606** [comment]
thank you, close this topic please :)
