### ISSUE TITLE
Logfile is enabled by default, documentation out of date?

### ISSUE THREAD

**Issue by justingit** [servocoder/RichFilemanager#123]
Looking at the docs at, 

https://github.com/servocoder/RichFilemanager/wiki/Enable-log-debug-in-PHP-connector

It states that you would want to edit the, filemanager.config.json file, change: 

    "logger": false,

to, 

    "logger": true,

then add, 

    "logfile": "C:/filemanager_log.txt"

(set to a valid filename). 

First off, logging seems to be enabled by default, even though this setting is set to, "false". secondly, it may be a bad idea to have an absolute server path in a json file, that can be read easily in the browser - it's leaking sensitive information about the backend setup. 

The php connector also has a logging setting, "logger" 

It is set to, "true" by default. This doesn't work well on my local Mac, running XAMPP - the directory set just isn't writeable. 

But, setting "logger" to, "false" has no effect - the logfile will still be attempted to be written. I have t change the sourcecode in connectors/php/application/Logger.php to instead write the logfile to somewhere the script has read/write access.

**Comment by servocoder** [comment]
As far as Richfilemanager stands for the concept of complete separation of cliet-side and server-side and due to security reasons, it's not possible to control server-side options with JSON configuration file. To do this you have to enable logger in the config.php file. The `logger` option in the JSON file output some workflow notes and extended error information to the browser console.

With regard to wiki, your assumption is correct, the article is out of date. I'm going to update it. I will also check why `logger` option in config.php file doen't take effect. Thanks for reporting.

**Comment by servocoder** [comment]
Bug fixed and added capability to define logfile path (dev branch). Wiki article is updated.

**Comment by servocoder** [comment]
Released in v2.3.0
