### ISSUE TITLE
Thumbnail image is shown but actual image broken

### ISSUE THREAD

**Issue by suresh-** [servocoder/RichFilemanager#135]
Hi,

I have directory outside of www root
/home/abcd/ftpdir

Everything works wonderfully well but only problem is with actual image is not loading, however the thumbnail is showing the correct picture and image can be downloaded.

Can you please let me know what could be the problem?

**Comment by servocoder** [comment]
That is because an actual image (in preview mode) is loaded using the direct absolute path by defaultю, however RFM can't define absolute path authomatically when you change root folder. There are way ways to fix that. Read the related Wiki articles: 
- [Handle preview URL](https://github.com/servocoder/RichFilemanager/wiki/Handle-preview-URL)
- [Specify user folder, configuration cases](https://github.com/servocoder/RichFilemanager/wiki/Specify-user-folder%2C-configuration-cases)
