### ISSUE TITLE
Filemanager given config file does not exist

### ISSUE THREAD

**Issue by wilsonld** [servocoder/RichFilemanager#161]
I am having trouble configuring Rich Filemanager to work with CKEditor.  It works fine with my local server but does not when I publish it to my website at Godaddy.com.  When accessing index.html I get the message Given config file does not exist (./config/filemanager.config.json) does not exist.  I also get the message Given config file does not exist (./config/filemanager.config.default.json).

I have all the files for Rich Filemanager located in a folder called filemanager in the CKeditor folder.

I think my problem has to do with baseurl which can be configured in the Index.html file.  I have tried changing the Index.html file with the following code but it doesn't help.

            <script type="application/javascript">
                $(function() {
                    $('.fm-container').richFilemanager({
                        baseUrl: 'filemanager/',
                        });
                });
            </script>

I'm not sure I have all the squiggly brackets correct and I'm not even sure I am on the right track.

Can anyone help me correctly configure this so it finds the filemanager.config.json file?  It works great on my local IIs server but not when published to Goddaddy.com.

Thanks,

Larry Wilson

**Comment by servocoder** [comment]
Hello, Larry!
I think you are on the right track. See the default `baseUrl`:
```
baseUrl: '.',	// relative path to the FM plugin folder
```

RFM assumes that `/config`, `/scripts` and other folders are at the same lavel as `filemanager.js` file. If have changed folders structure you have to change `baseUrl` to the correct relative path, like `./filemanager` OR absolute path: `http://domain.com/filemanager`.

Unfortunately I can't give you additional info since you haven't provided your folders structure. Try my advices, if they will not help then attach screnshots which depicts your folders structure and also provide comprehensive description, please.

**Comment by wilsonld** [comment]
Hi Pavel,

Thanks for the reply.

What I find is that whatever I put in the script in the index.html for baseurl it seems to be ignored both on my local server and the godaddy.com server.  When I put in a path that shouldn’t work at all (such as ‘./test’) filemanager continues to work on my local IIS server and it doesn’t on the godaddy.com server.

I haven’t changed the files structure at all.  The filemanager folder is a subfolder of the ckeditor folder.

I have a test file that you can take a look at if you could.  The url is  <http://westchester-kensington.com/ckeditortest> http://westchester-kensington.com/ckeditortest. 

Here is the result on my local server:

Here is the result on my godaddy.com server:

Anything you can do to help would be appreciated.

Thanks, Larry

**Comment by servocoder** [comment]
I guess you tried to attach images replying to email. Seems this doesn't work at GitHub. Please edit your message at GitHub directly, because I can't see any screenshots.

> What I find is that whatever I put in the script in the index.html for baseurl it seems to be ignored both on my local server and the godaddy.com server.

`index.html` is a wrong place . The correct place to specify `baseUrl` option is `config/filemanager.init.js` file (supposed, that you created it by copy and rename [`filemanager.init.js.example`](https://github.com/servocoder/RichFilemanager/blob/master/config/filemanager.init.js.example) file).

**Comment by wilsonld** [comment]
I was on the wrong track.  I was trying to set the baseurl in the script settings in the index.html file rather than the filemanager.init.js file.

After getting your reply, I have tried various baseurl settings in the file filemanager.init.js file, including the absolute path.  Using relative path and '.' (the default), and '/ckeditor/filemanager' I can get it to work using my local IIS server but it still won't work on my godaddy.com server.  I also tried the absolute path  'http://westchester-kensington.com/ckeditor/filemanager' on the godaddy.com server and that didn't work either.

So, I don't think it's something related to the file structure or the baseurl that's causing the problem.  I think there is something going on with the godaddy.com file server, either in file permissions or something else.  Here is the screenshot of my file structure anyway.

[File structure screenshot.docx](https://github.com/servocoder/RichFilemanager/files/930767/File.structure.screenshot.docx)

One question I have is what version of php is now required to make filemanager work?  I have version 5.6 running on my local IIS server and godaddy.com only supports up to version 5.4.  Is that a problem?

**Comment by servocoder** [comment]
> I don't think it's something related to the file structure or the baseurl that's causing the problem.

Yeah, it seems fine

>One question I have is what version of php is now required to make filemanager work? I have version 5.6 running on my local IIS server and godaddy.com only supports up to version 5.4. Is that a problem?

PHP 5.4 should be enough. I don't use any PHP features that require version > 5.4. It would be a good idea to check your http server log files.

**Comment by wilsonld** [comment]
I called godaddy.com today and they weren't much help.  They gave me some additional entries that I could put into my web.config file to hopefully generate an error message on the browser when the problem occurs, but that didn't help because Rich Filemanager seems to trap the error and gives me the "given file does not exist" message in the red box and no other detailed error information is generated.

By the way, I have full trust set up in my web.config file.  I know there have been issues in the past regarding running code in medium trust on godaddy, so that shouldn't be the problem here.

So, at this point, I am stumped as to how I can get this to work on a godaddy shared server.  I didn't seem to have any problems with prior versions of the filemanager but this one simply won't work for me.

**Comment by servocoder** [comment]
I have investigated your problem deeply. Seems you set invalid path to file browser. This is your code:
```
CKEDITOR.replace( 'editor1', {
	filebrowserBrowseUrl: '/ckeditor/filemanager/index.html',
});
```

Change the `filebrowserBrowseUrl` value to correct absolute path:
```
CKEDITOR.replace( 'editor1', {
	filebrowserBrowseUrl: '/ckeditortest/ckeditor/filemanager/index.html',
});
```
Or correct relative path:
```
CKEDITOR.replace( 'editor1', {
	filebrowserBrowseUrl: './ckeditor/filemanager/index.html',
});
```

**Comment by wilsonld** [comment]
Thanks for the response.

I tried each of the above changes.  The first change got me a file not found message on both my local server and the godaddy server.  The second using the relative path worked again on my local iis server but got me the familiar red boxes with given json configuration files do not exist.

I also set the filemanger.init.js file back to the original example, eliminating the baseurl attempt in that file.  Same story, worked on local iis server but not on godaddy.

Then, I decided to try to simplify the code by eliminating the master file as it has some calls to various jquery javascript files thinking there might be a conflict with the versions used by filemanager.  I created a new file which  is http://westchester-kensington.com/ckeditortest2.  This file has no master file attached but also calls the local ckeditor.js file in the ckeditor folder instead of the one referenced on the ckeditor site.  Still no luck as the new, simplified ckeditortest2.aspx file gives the same results (works on my local iis server but not on godaddy.com).

You can take a look at the new file and the source code and try to run it, but I'm not sure there are any new clues there.

**Comment by servocoder** [comment]
Ok. It's my final answer to this topic since I'm strongly believe that this is your server configuration issue, and I will explain why. The JSON configuration file should be web-accessible via HTTP protocol. That means if I type the url associated with JSON configuration file into adress bar of my browser I will see its content. Try these links:

http://fm.devale.pro/config/filemanager.config.json
http://fm.devale.pro/config/filemanager.init.js

I tried to do the same for config file on your host but I had no luck. Of course I don't know the configuration of your server, but I assumed that url to config file may looks as (in case your domain associated with /ckeditor folder in your file structure):

http://westchester-kensington.com/ckeditortest/filemanager/config/filemanager.config.json

However I got error. Once you manage to open `filemanager.config.json` with browser address bar you will bw able to use RFM. You can come back and request my help with the correct url, in case you still experience problems to run RFM haveing web-accessible JSON config file.

**Comment by wilsonld** [comment]
Problem Solved!  Godaddy doesn't have the mime type handler installed on its web server.

You didn't have the correct url which should have been:

http://Westchester-Kensington.com/ckeditor/filemanager/config/filemanger.config.json.

When I went directly to the above url with my browser, I got the error that the json mime handler was missing and I should install the handler on the iis server.  Since I don't have access to their server config file, there is another way to install it using the web.config file.

The entry for the web.config file on asp.net is:

  <system.webServer>
       <staticContent>
              <mimeMap fileExtension=".json" mimeType="application/json" />
       </staticContent>
  </system.webServer>

I put this in my web.config file and it worked!

I had called godaddy to try to get some help on this, but the agent I talked to didn't pick it up.  Your last suggestion is what unlocked it for me.

Thank you for your patience in helping me resolve this.  It was driving me nuts.  Hopefully, you can file this away for future reference for those of us who are using the filemanager on iis servers with asp.net.

**Comment by servocoder** [comment]
I'm glad you solve the problem, enjoy RFM )
