### ISSUE TITLE
Asp.Net Core Support

### ISSUE THREAD

**Issue by sinanbozkus** [servocoder/RichFilemanager#163]
Hello,

I want to use RichFileManager with **Asp.Net Core.** Is there any connector for this ?

**Comment by servocoder** [comment]
It exists, but outdated. See `/connectors` folder and also check issue #114. But take in mind that ASHX is a bit uptdated as well due to last features implemented. So there are two options: you can update ASHX connector if it fits you, or write ASP connector from scratch. Anyhow I would appreciate if you take a lead on any of connector and become a maintainer.

**Comment by sinanbozkus** [comment]
Ok, I will publish the connector in a few days. I'm working on it.

**Comment by servocoder** [comment]
Great. Use this [wiki article](https://github.com/servocoder/RichFilemanager/wiki/API) as an API interface. Also keep in mind that the "replace" action will be removed in the next release. Fell free to ask in case of any issues.

**Comment by servocoder** [comment]
If you are going to use PHP connector as an example for implementation (I recommend you to do, because it supports all client-side features), I would strongly recomend you to examine ["refactored"](https://github.com/servocoder/RichFilemanager/tree/refactored) branch, which implements new security model and will be released in the next version. The refactoring is in progress, be aware.

Pay particular attention to the backend [configuration file](https://github.com/servocoder/RichFilemanager/blob/refactored/connectors/php/richfilemanager/config/storage.local.php). It will give an idea of the most of backed features of PHP connector which I would like to be implemented for Asp.net connector. The location of the file may be changes due to refactoring process.

**Comment by servocoder** [comment]
Hi @sinanbozkus !

Since the latest release v2.4.0 PHP connector is moved to the [separate repository](https://github.com/servocoder/RichFilemanager-PHP) and should be installed via composer. You can do the same for the ASP connector that you are working on. Are not you?

Check out [new location](https://github.com/servocoder/RichFilemanager-PHP/tree/master/src/config) of configuration files.

Please let me know if you have any impediments while implementing ASP connector. Also inform me if you stoped working on it and not going to proceed. I will close the issue in this case. Thanks anyhow.

**Comment by sinanbozkus** [comment]
I'm working on, almost done.

**Comment by servocoder** [comment]
Latest version brings many changes, mostly security related, making RichFilemanger more safe and robust. Unfortunately this resulted in some backward incompability changes. Some of them you can check in the [changelog](https://github.com/servocoder/RichFilemanager/blob/master/changelog) file. The [wiki](https://github.com/servocoder/RichFilemanager/wiki) is up to date with the latest release.

As for you particular error - it comes from the server-side configuration file (see [php example](https://github.com/servocoder/RichFilemanager-PHP/blob/master/src/config/config.local.php)). The client-side expects some configuration options that should be passed from the server-side, because it's unsecure to define them in [JSON configuration file](https://github.com/servocoder/RichFilemanager/blob/master/config/filemanager.config.default.json).

The **`ignoreCase`** option that is mentioned in your error message is one of such options. You cound find this option in the PHP config file linked above, but it is absent in the JSON configuration file. This behavior is well described in the "Implicit configuration options" section if [Configuration options](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options#implicit-configuration-options) wiki artickle. You could also note in this article, that all slient-side options that should be passed from the server-side (your connector) are marked as **(IMPLICIT)**. Make sure you pass all of them from your connector.

To pass all IMPLICIT configuration options you have to use [**`initiate`** API method](https://github.com/servocoder/RichFilemanager/wiki/API#get-initiate). You could examine the [implementation](https://github.com/servocoder/RichFilemanager-PHP/blob/master/src/Api/LocalApi.php#L27) of PHP "initiate" method as an example.

**Comment by sinanbozkus** [comment]
Thanks,

Is online demo (http://fm.devale.pro/) last version ? I can track network (json) traffic.

**Comment by servocoder** [comment]
It's just an example, to get the complete list of mandatory implicit options see link to implementation of PHP "initiate" method that I gave you in the prev post: 

```php
        $shared_config = [
            'security' => [
                'readOnly' => $this->storage->config('security.readOnly'),
                'extensions' => [
                    'policy' => $this->storage->config('security.extensions.policy'),
                    'ignoreCase' => $this->storage->config('security.extensions.ignoreCase'),
                    'restrictions' => $this->storage->config('security.extensions.restrictions'),
                ],
            ],
            'upload' => [
                'fileSizeLimit' => $this->storage->config('upload.fileSizeLimit'),
            ],
        ];
```

**Comment by servocoder** [comment]
Have you solved the issues?

You mentioned, that your connector is "almost done", is there any planned release date for it?

**Comment by servocoder** [comment]
How it's going? Do you need any help?

**Comment by sinanbozkus** [comment]
It is ready, I will send it on today.

**Comment by servocoder** [comment]
I have merged your PR.
You did a great job! Thank you for the contribution.

I noted that you created new folder "aspnetcore" for your connector. The old one located in the "asp" folder is outdated. Could we replace connector located in the "asp" folder with the yours?

Also I would ask you for 2 things:

1. Move configuration options to the separate file for easy setup.

2. Write a `ReadMe.md` doc file with detailed description on how to deploy, setup and configure of your ASP.net connector? Similar to PHP connector [article](https://github.com/servocoder/RichFilemanager-PHP/blob/master/ReadMe.md). I will create a new article at the base of your file in the wiki [Connectors section](https://github.com/servocoder/RichFilemanager/wiki#connectors).

**Comment by servocoder** [comment]
Hey @sinanbozkus 
Can I expect you to answer my questions of previous post?

**Comment by servocoder** [comment]
ping

**Comment by servocoder** [comment]
Your connector is released in v2.5.0
Thanks for your time and contribution!

I close the issue, but if you will have time for my requests (see my previous messages) feel free to continue discussion here. If you would like to develop and enchance your connector I'm open for the discussion as well.

**Comment by FazelMan** [comment]
How can I use this library in ASP.NET MVC?
Is there a perfect example of this code?

**Comment by sinanbozkus** [comment]
This connector is for ASP.NET Core, not ASP.NET MVC.

**Comment by servocoder** [comment]
@sinanbozkus, could you provide things that I asked you on 24 May ?
It would be really helpful to have guidelines with examples for your connector in order to create wiki article based on it. Thanks in advance.

**Comment by tharris9d** [comment]
Has anyone implemented these options for granular security in .net core? 
function fm_authenticate()
function fm_has_read_permission($filepath)
function fm_has_write_permission($filepath)
We are looking for some simple examples to be able to add user rights.
Thanks, Tom
