### ISSUE TITLE
File type is not allowed Error When Renaming Files

### ISSUE THREAD

**Issue by jsooter** [servocoder/RichFilemanager#178]
I believe this is a config issue since I don't see an API call. I've looked but I can't find how to enable file renaming. Folder renaming appears to work as expected.

**Comment by jsooter** [comment]
I think this may be caused by the extension being passed to the client with a period e.g. .png instead of png... I'll close this issue.

**Comment by servocoder** [comment]
Ok. One note: Since the latest version (2.4.0) you don't have to send "extension" attribute from the server-side for files. It's taken from the filename at the client-side now. You can remove it from the response of your connector. Also check the [changelog](https://github.com/servocoder/RichFilemanager/blob/master/changelog) for updates and backward incompability changes.
