### ISSUE TITLE
regarding your alertify.js version

### ISSUE THREAD

**Issue by simogeo** [servocoder/RichFilemanager#199]
Hi @servocoder : I hope you're fine.

I'm sorry, I'm posting my question here because issues are not enabled in your [alertify.js repo](https://github.com/servocoder/alertify.js).

I tried to switch from the old alertify.js version to your maintained version and I get a basic issue I don't understand.

I use basics success / error method ... but it trigger the following message : 

`TypeError: this.parent is null[En savoir plus]  alertify.js:1:4729`

Any idea ? thanks

**Comment by servocoder** [comment]
Hi @simogeo 

I'm fine, hope you too!

Yeah, I wasn't able to release alertify v2 due to lack of time.

I'm able to reproduce the problem. The default parent is `document.doby`, but for some reason it's ignored. To not wait a fix you could use a simple workaround by forcing `parent` option:

```javascript
alertify.parent(document.body);
alertify.success("Success!");
```

Here is working example:
https://jsfiddle.net/ur5r46yx/

**Comment by simogeo** [comment]
Thanks for your reply. I'll have a try but maybe wait for a cleaner version. Anyway, I'll stay tuned ! thanks again.

**Comment by kamilski81** [comment]
@simogeo I had the same issue in my project. Diving into the source code I found that the 'parent' property of alertify is set only on reset() method. So, I did call to alertify.reset() just after initialize my SPA

**Comment by simogeo** [comment]
Thanks for the ping @kamilski81 !
