### ISSUE TITLE
Client-side output files filtering

### ISSUE THREAD

**Issue by servocoder** [servocoder/RichFilemanager#204]
The `type` parameter is the legacy from original RichFilemanager
According to the new security model it's not secure to pass parameter to the server in order to set allowed files extensions list. Thus `type` parameter is ignored in the last versions.

However it might be a good idea to use `type` parameter for client-side filtering, just to hide non-image files in case the type `image` is set. It will not affect files list returned in the connector's response. You have to use server-side config for this.

Also, since you may want to define you own extensions list for `images` filter I think the JSON config file should be extended with `filter` option, where you can define your own associations. Example:

```json
{
  "filter": {
    "images": ["jpg", "gif", "png"],
    "media": ["mp3", "avi"],
    "custom": ["pdf", "md", "doc"]
  }
}
```

Raised from https://github.com/servocoder/RichFilemanager-PHP/issues/7

**Comment by servocoder** [comment]
Criterias:

1. Filtering should affect both: files tree (left pane) and files view (right pane)
2. The `filter` should be the upper-level section in the JSON config file, right before `viewer` section
3. The [type](https://github.com/servocoder/RichFilemanager/wiki/Passing-parameters-to-the-FM#restrict-the-view-to-images) query parameter should be renamed to `filter`

**Comment by Saso222** [comment]
I'll do it. Can you assign it to me?

**Comment by servocoder** [comment]
I can't assign you since you are not a creator of this issue. Go ahead eitherway.

**Comment by Saso222** [comment]
When a user tries to upload a file that is not in the list of extensions for the current configuration, shall we prevent them for doing it? Or let them do it but don't show them later?

**Comment by servocoder** [comment]
The second option in correct:
>  let them do it but don't show them later

Your PR should affect client-side solely. Don't involve connectors, please.
Btw, don't bother to minify scripts, I will do it later.

**Comment by servocoder** [comment]
I can see you applied filtering to the fileupload as well.

I don't think we need this because this feature is not intended to be used as restriction. Eventually every user of RFM can change query param `filter`, so you can't rely on this. Server-side config is the right place for such restrictions. 

This feature is for filtering out specific files in folders to display only images or media files. Later we can UI icons to filter lists by mouse click event without changing URL.

Let me know if you can see any case when we need to apply filtering to files upload part.

**Comment by Saso222** [comment]
Hello,

I don't fully understand what you mean. Is it the:
`$('#fileupload').attr('accept', shownExtensions.map(function(el){return '.'+el;}).join());`
part?

What I intended with this was to show the user the subset of file extensions in the browser file explorer. But it is not a restriction indeed, since he can just select "All files" in the explorer.

If you mean the piece of code added to the 'fileuploadalways' and so on events, I was trying to do what we talked about in the PR: let the user upload the files but do not show them in the lists later. The file is correctly uploaded and, if you don't pass the `filter` query param later, it'll show as expected.

By the way, I found a bug when passing the query param and the filter section is not specified neither in the config.json nor in the config.default.json. It throws an undefined error in the `getFilteredFileExtensions` function. Shall I push the change to the same branch?

Thanks.

**Comment by servocoder** [comment]
I see, thanks for the clarification. Sounds reasonable.
I haven't tested your code yet, just performed a quick code review, so seems I misunderstood some parts. Ok, leave it as is.

As for the new bug you discovered, create new PR on the "dev" branch, please.

**Comment by servocoder** [comment]
Hey @Saso222 
I have greatly exptended the concept of filtering
Now it's possible to apply filtering directly in the UI with buttons in the header.
Capability to perform filtering via URL params remains without changes.
Just note that you have to set "image" insted of "images" filter now.

![screenshot_1](https://user-images.githubusercontent.com/1310273/29057296-06a81ccc-7c12-11e7-915e-68d8e47ab680.png)

Changes in UI highlighted on the screenshot:

1. refresh of currently open folder content
2. client-side filtering section

All this will be release in the v2.5.2 soon
You can get an actual code at the "dev" branch.
I would appreciate if you will find an opportunity to test it before release.
