### ISSUE TITLE
Java Servlet 2.5 With Google server 

### ISSUE THREAD

**Issue by Mahdi-Roozbahani** [servocoder/RichFilemanager#221]
This is a great library. I am kind of lost in deploying this into my Java Web Application.

I am using Eclipse with GAE (Google App Engine) and Servlet 2.5 (I am not using spring in my web-app). I would appreciate it if you can provide me some guidance that how I can implement RichFilemanager into my web-application.

**Comment by servocoder** [comment]
@fabriceci is the maintainer of Java connector. Address you questions to him.

**Comment by fabriceci** [comment]
There is in fact 2 java connectors at the time being. This is confusing, this has happened because we updated an old connector at the same time, and we used different versions of java/servlet. But hope to solve this in the future.

I updated one version in the java folder (connector/java), I tested the connector only with spring MVC (but it should work without), it uses Servlet 3.0 upload and java 8 (do not seem to fit your requirement)

But there is another version in the JSP folder (connector/jsp), which uses java 7 and Servlet 2,5 upload. This is the version you should use. You can find the root jsp file here : https://github.com/servocoder/RichFilemanager/tree/master/connectors/jsp

**Comment by Mahdi-Roozbahani** [comment]
@fabriceci  thx for the response.

I read that documentation. I have issues in two parts of it.

- Uses Java Connector code /java/src/main/java/ com.fabriceci.fmc.util.* and c.f.f.error.* packages as a relative dependency (or copy java classes and change build.gradle)

Because in my web app, I don't have any gradle, I have pom, and web.xml and etc. What do suggest on this?

The second part is:

- You should copy the libraries/java/bin directory content for instance to the WEB-INF\classes directory (in case you are using a Tomcat application server) to make everything work

I don't exactly understand this part, and what I am supposed to do. In github, do I need to download just this part, and that's it? I would appreciate it if you could explain it more.

**Comment by fabriceci** [comment]
I'm not the author of this version maybe @servocoder can ask to the author to join the thread.

For you first question, it's easy to use maven(pom) instead of gradle, There are no much dependency if you check the buid.gradle.

When it's done, I think you should just copy the files and add the filemanager.jsp at your project.

(I don't understand the purpose of the second part)

**Comment by Mahdi-Roozbahani** [comment]
@servocoder  @servocoder  Great, Hope I can solve it and use this great library in my web app company project.

By taking a quick look at the code, I also realized that in maybe two of java files, FileOutputStream has been used. According to this https://stackoverflow.com/questions/8090670/google-appengine-not-supporting-fileoutputstream, unfortunately GAE (Google App Engine) won't allow the usage of this library. If there is any workaround for this, I would be happy to implement it.

**Comment by fabriceci** [comment]
The code is easy to read, don't hésitate to make modification to suit your needs.

In the new version of the connector, I only use one time this class to Zip a folder, I don't know if there is a workaround but you can always disable this feature in the client configuration.

**Comment by servocoder** [comment]
@Mahdi-Roozbahani If you think your modification will be useful fo rothre members create a Pull Request then. Once @fabriceci approve it I will include it in the package.

**Comment by servocoder** [comment]
Btw @gmkll may help you with `connector/jsp` connector. Hope he will respond you once receive notofication.

**Comment by gmkll** [comment]
Hi @Mahdi-Roozbahani, hi all,

The second part (_You should copy the libraries/java/bin .._)  just means that this is the output folder, if you use gradle build. There are no compiled classes checked in at the moment, except org.json, which you could otherwise find in a lot of libraries (with different licenses, though). So you have to build the JSP connector from source yourself anyway (gradle would then also build a jar into build folder). So nothing special here. 

Hopefully this helps for now. @fabriceci I may try to merge the connectors ..

**Comment by Mahdi-Roozbahani** [comment]
Thx to you @servocoder @fabriceci @gmkll.

Today, I tried to add this connector's different parts manually, and realized that many famous clouds like Google, AWS, Azure, etc do not let users to use "java.awt.*" and "java.nio.*" because of the security problems. So, problem is a little bit bigger than what I expected and thought. Any inputs?

**Comment by gmkll** [comment]
That´s what may be [google-cloud-nio](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-contrib/google-cloud-nio) is made for - building a wrapper around nio in this case Google Cloud? That´s a task to do this!

**Comment by fabriceci** [comment]
@gmkll I have already started the merge (but it's more than a simple merge), I will try to finish that quickly, but I can put the advancement on Github if you want.

**Comment by gmkll** [comment]
Ok, that would be nice, may be I could throw in some input.

**Comment by servocoder** [comment]
@gmkll Please take a look in the RFM Skype group. Fabrice is trying to get in touch with you there.

**Comment by servocoder** [comment]
@fabriceci @gmkll how is your progress on new Java connector?

**Comment by servocoder** [comment]
I think this discussion has exhausted itself.
