### ISSUE TITLE
Feedback: Redundant API Method?

### ISSUE THREAD

**Issue by stevelittlefish** [servocoder/RichFilemanager#248]
I much prefer the new API to the old Filemanager API, but there was one method that really confused me, and that's the "download" API call.  To me it seems unnecessary to have it behave differently for Ajax and non-Ajax calls.  In my code I pretty much do this:

if request.is_ajax:
    return getfile()
else:
    return contents_of_file(the_file)

Basically, to me it seems that the Ajax version is just the same as "getfile", and the non-Ajax version just sends the file.  It was a bit confusing because none of the other API calls behave like this.

**Comment by servocoder** [comment]
Ajax call is required in order to check whether the file is valid and whether all requirements for the "download" operation. If it's invalid the error is handled at the client-side. Otherwise a regular GET request is performed to download file.

If you can suggest a better solution I would extpect it former as PR. Thanks.
