### ISSUE TITLE
Does "expandedFolder" option works?

### ISSUE THREAD

**Issue by dsu** [servocoder/RichFilemanager#255]
I would like to set the current directory of a file manager. Preferably by JS API.
I have tried _expandedFolder_ parameter. I can see a second Ajax request that fetches a content of that directory, but file manager shows root directory. 
It doesn't work in demo application either:
[http://fm.devale.pro/index.html?expandedFolder=My](http://fm.devale.pro/index.html?expandedFolder=My)

**Comment by servocoder** [comment]
It works. It expands the folders in the filetree (left panel) according to the path you specified in the `expandedFolder` parameter. I can see it doesn't update items in the right panel. And I don't think it's a good idea taking into account that RFM navigates folders consequently, one by one. This means you will see contents of the following folders when open `/my/nested/folder` folder:

- main folder items
- "my" folder items
- "my/nested" folder items
- "my/nested/folder" folder items

The delay will be minimal. As much as is required to fetch contents of the next folder. But most likely your users will be able to observe that right panel has been updated 4 times before they can see contents of the `/my/nested/folder` folder.

**Comment by doziteh** [comment]
This is poor design. I am sorry for strong words but thats what it is.
Expanding it only in the filetree is not enough and even confusing. If two computer professionals: dsu and myself cant figure it out, it is hard to expect from less experienced users to do so.
If I may add this was one of the features why I choose RFM for our project, 
Why have you dropped it?
Because of flickering? I personally didn't mind the flickering moreover its was a sign that you are going deeper into the folder structure.
I vote for this feature to be restored as it was in previous versions.

**Comment by servocoder** [comment]
I give up before computer professionals and experience a great shame of that. I promise to pay close attention to this issue.

**Comment by servocoder** [comment]
You can try with the latest commit. Should work now.
