### ISSUE TITLE
set param browseOnly

### ISSUE THREAD

**Issue by rhyudek1** [servocoder/RichFilemanager#29]
is there any chance to edit parameters in filemanager.config.json in php through the object $fm

regards

**Comment by servocoder** [comment]
It should be possible, but due to implementation of plugins support I have removed this capability accidentally. I am going to take a look and bring it back soon.

Anyway you still could, but not through $fm object. Before $fm instance is initialised you are able to read config data from default config file, modify and write it to a new config file on the fly. Something like that:
```
$scriptsPath = "/your/path/to/folder/scripts/";
$configFile = $scriptsPath . 'filemanager.config.json';
/* creates config file if not exists */
if(!file_exists($configFile)) {
    $configDefaultFile = $scriptsPath . 'filemanager.config.default.json';
    $configDefault = json_decode(file_get_contents($configDefaultFile), true);
    /* modify $configDefault here */
    file_put_contents($configFile, json_encode($configDefault));
}
```
I don't force you to use this way, you can wait for a fix. I gave this example for a reference mostly.

**Comment by servocoder** [comment]
Ok, I have a bit more time for your problem now. Looking thoroughly at the subject of the current issue I found that you want override `browseOnly` option which relates to the client-side solely. Passing extra config to the constructor of `$fm` will take effect only for server-side related options like `fileRoot` etc. It is because the client-side have been already initiated with options from the config file at this point.

Thus the only way for you to override `browseOnly` option is to do as I suggested in the answer above. You have to execute this code before the 'filemanager(.min).js' file is attached to the page. Put it at the BEGINNING of the page where you are going to include FM html an js files - `index.html` by default.

On the other hand it's more easy if you have to override some server-side options. Just make a replacement in the `filemanager.php`:
```
$fm = BaseHelper::getInstance();
```
to
```
require_once('LocalFilemanager.php');
$fm = new LocalFilemanager([
    'options' => [
        'fileRoot' => '/your/file/root/'
    ],
]);
```
Either way I'm going to modify `filemanager.php` file to make thing easier.

**Comment by servocoder** [comment]
Done.
You now able to override default configuration in [filemanager.php](https://github.com/servocoder/RichFilemanager/blob/master/connectors/php/filemanager.php).
But again, it affects only options which are related to server side, `browseOnly` is not the case. There is a plan discussed in #32 to divide the config file into 2 files to separate server-side options from client-side options to avoid the confusion.
