### ISSUE TITLE
Release 1.1 roadmap

### ISSUE THREAD

**Issue by servocoder** [servocoder/RichFilemanager#41]
I'm going to update this list with requested feature for 1.1 later.

Here the list of thing which is done and available at [dev branch](https://github.com/servocoder/RichFilemanager/tree/dev):
- js file reworked to become a plugin
- some ajax async calls replaced with deferred chains (based on #21)
- new Java connector (#21)
- new nice notifications, based on alertify plugin on my fork (#25)
- theme concept was reworked, base assets created, no need to duplicate all assets for new theme
- started with demo page with examples for different usage cases
- many changes in html templates to make thing more organaized
- upload popup dialog now scrollable

**Comment by servocoder** [comment]
Things done at the "dev" branch:
- capability to preview images and media files with absolute path along with connector path (#31)
- fully separated server and client config files, with optional ability to override common options (#32)

**Comment by servocoder** [comment]
Backward incompatible changes:
- API method "getinfo" was renamed to "getfile"
- API method "add" was renamed to "upload"
- many of [client-side config options](https://github.com/servocoder/RichFilemanager/blob/dev/scripts/filemanager.config.default.json) were moved to server-side config file ([PHP example](https://github.com/servocoder/RichFilemanager/blob/dev/connectors/php/config.php)), so every connector's maintainer have to implement those options for his connector: @jlaustill, @fabriceci, @djb15

**Comment by fabriceci** [comment]
Wow! You made a lot a work, awesome! I'm going to take time to look at the code's modifications.

I have 3 suggestions before to release this version:

1) **complete separation** : config

There are now duplicate parameters (examples : "security", "exclude", "upload", etc.) in client/server configuration.

This is confusing and not necessary, the only correct one is the server config. During the plugin initialization, the plugin should retrieve the correct configuration through the connector.

2) **complete separation** : repository

Ideal situation : I use a package manager like Bower to handle my JavaScript files and another one for my server connector. 

- I don't want to download all connectors each time I update the plugin.
- The server code should be separate to be available in a package manager like Composer/Gradle.
- I don't know want to download a new version of the plugin where there nothing to me, just bug fixes in connectors I don't use.

The client and server should have a different lifetime now. 1 repository for the plugin , and 1 per connector.

3) JSON Standardization

We discuss about that. We should reach a point where the JavaScript plugin can evolve without break connectors (in view of the lot of work you did, maybe after this version).

We should keep in mind that there are a lot a chance that many maintainers will update very tardily (or never) their connectors.

If you intent to standardize the API, you should do this now because I think this is the last big modification in the API. Doing this after involve asking again to the maintainers to update their connectors.

What do you think?

Again great work!

**Comment by servocoder** [comment]
Hi @fabriceci, thanks for appreciating my work.
With regards to your suggestions:

1) Yeah, I also like the idea to move duplicate parameters to one place. If you remember I described the "init" method for this purpose ([here](https://github.com/servocoder/RichFilemanager/issues/32#issuecomment-240338790) and [here](https://github.com/servocoder/RichFilemanager/issues/31#issuecomment-245193794)) and I even have implemented the "init"method few commits ago, but removed it later.

The first problem here is that connector's maintainer should care that his configuration for "security" or "upload" options are compatible with client-side code. For example, maintainer would like to use regex in "uploadRestrictions" in the connector, but he can't because the backward compatible will be broken.

The second problem is that not all client-side parameters of the sections are used at the backend. Let's consider "images" and "upload" sections. As you can see the connector doesn't use `images`.`showThumbs` and `upload`.`multiple` parameters and they are not exist in server-side config, since they are client-side related only.

In light of the above I have decided to remove the "init" method yet, because I don't have a solution at the moment. Feel free to share your ideas in #32 if you have any. I will gladly revert the "init" method back once I have a solution.

2) Good idea, I'm gonna add this point to my todo list, but the implementation will be postponed since there are other things with the higher priority in the list.

3) I have already stated the work on JSON API implementation. It will take some time and will bring severe changes in the code. I'm gonna release it in 1-2 weeks.

Thanks for your ideas, I appreciate your contribution.

**Comment by servocoder** [comment]
I am pleased to present a new major release of RichFilemanager v.2.0.0 (instead of v.1.1 due to a lot of major and incompatible changes)

Release notes:

- migrated frontend to knockout.js
- removed a number of the application plugins (tinysort, filetree, impromptu, liveSearch); their functionality has been replaced with own implementation
- grid view icons implemented via css styles (#47)
- capability to preview images and media files with absolute path along with connector path (#27, #31)
- completely rewritten and standardized Rich Filemanager API that follows JSON API best practices (#37)
- configuration splitted into two files: server and client config files (#31, #32)
- implemented "initiate" request to provide ability to override client-side configuration options (#29, #32)
- refactored client-side configuration files: deleted obsolete options, some options or sections were moved/renamed (actual configuration description is in WIKI)
- implemented actions-based access management (#24)
- greatly improved security for PHP connector, a number of vulnerabilities were fixed
- handle large files download in PHP connector (#56)
- "languages" folder moved to the root FM folder
