### ISSUE TITLE
Can't open rootFolder

### ISSUE THREAD

**Issue by SlitYahoo** [servocoder/RichFilemanager#46]
Hi! I Get Server error when I set in filemanager.config.json
        "serverRoot": true,
        "fileRoot": "MyFolder/",
MyFolder is located in domain.com/MyFolder.
Filemanager si located in domain.com/MyFolder/NewFolder/filemanager/index.html

**Comment by servocoder** [comment]
Where is your userfiles folder supposed to be located?
Cause you don't need to change "fileRoot" option if you use default folder structure of FM and your userfiles folder is locatead under the domain.com/MyFolder/NewFolder/filemanager/

Your current setup means that your userfiles folder is located in [server_root_folder]/MyFolder/
Which is strange because I doubt I want to save user files directly to /MyFolder, it looks more reasonable
to specify "fileRoot" as "MyFolder/userfiles" in that case. And don't forger to create the specified folder.

**Comment by SlitYahoo** [comment]
I want to have ability to delete filese in domain.com/. By setting property the way I describe above I can open folder using exclusiveFolder property. So I can open domain.com/MyFolder but I can't open domain.com/. I thought it worked few days ago :-)

**Comment by servocoder** [comment]
You should check your folder permissons.
I don't know what you try to achieve but anyhow it seems strange for me that you set "fileRoot" folder to "domain.com/MyFolder" which is parent for the FM folder.

**Comment by SlitYahoo** [comment]
Thanks man :-) you are very bright. The problem was folder premission
