### ISSUE TITLE
When filename has en or em dash in his name File Manager returns server error

### ISSUE THREAD

**Issue by SlitYahoo** [servocoder/RichFilemanager#55]
When filename has en or em dash in his name, File Manager returns Server error on opening folder containing that file.
I am using Filemanager on XAMPP Windows 10.

**Comment by servocoder** [comment]
Indeed, it's a problem with specific symbols in file names on Windows. PHP on Windows uses the Legacy "ANSI APIs" exclusively for local file access, which means PHP uses the System Locale instead of Unicode. I wasn't manage with hot fix for that, because I have other things to do with a higher priority at the moment. 

BTW there is no problem on Linux, so if you use Windows for testing purpose solely it will be simplier to remove files with em dashes, or you could perform fix by yourself and make PR. Anyhow thank you for reporting the problem.
