### ISSUE TITLE
Changes in filemanager.config.json seem to have no impact

### ISSUE THREAD

**Issue by vgiotsas** [servocoder/RichFilemanager#65]
I'm trying to set the upload policy to `ALLOW_ALL` in the `scripts/filemanager.config.json` configuration file, but it seems to have no impact. 

Only after I changed the configuration options in `connectors/php/config.php` I managed to allow uploads for all file extensions. It seems that the options in `scripts/filemanager.config.json` are not read by the file manager.

**Comment by servocoder** [comment]
Yeah, server-side options have higher priority over client-side options.
Initial request to the server connector returns a list of config options to override ones which are common for both client and server sides. I know it's confusing. Perhaps we need some new config option to allow/deny this behavior. Such option may be defined only at the server-side (in `config.php` e.g.) due to security reasons. Is that idea good for you?

**Comment by vgiotsas** [comment]
Thanks for the response! Yes, I think that would be a good idea. The confusing thing is that some changes in the json configuration file have effect and some others do not.

**Comment by servocoder** [comment]
Implemented at the [dev branch](https://github.com/servocoder/RichFilemanager/tree/dev). By default overwriting of client-side configuration options is disabled. Can be enabled with `overrideClientConfig` option in the [configuration file](https://github.com/servocoder/RichFilemanager/blob/dev/connectors/php/config.php). The feature will be included in the next release.

All the things regarding to the configuration options precedence and overwriting process are detailed in the updated [Configuration options](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) wiki article.
